/* This file is part of Spectrum3D.

    Spectrum3D is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Spectrum3D is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Spectrum3D.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <gtk/gtk.h>
#include <string.h>
#include <GL/gl.h>
#include <GL/glu.h>

#include "config.h"
#include "preferences.h"
#include "spectrum3d.h"

char prefPath[100], rcPath[100];

int sizeofPrefInt = 6;
PreferenceInt preferenceInt[6] = {{&spectrum3d.width, 600, 50, 2500, "spectrum3.width"}, {&spectrum3d.height, 300, 50, 1500, "spectrum3.height"}, {&spectrum3d.interval_display, 100, 100, 500, "spectrum3.width"}, {&spectrum3d.interval_rt, 150, 100, 500, "interval_rt"}, {&priority, 50, 50, 80, "priority"}, {&spectrum3d.frames, 100, 50, 400, "spectrum3d.frames"}}; 

int sizeofPrefGLFloat = 7;
PreferenceGLFloat preferenceGLFloat[7] = {{&spectrum3d.presetX, -0.7, 0, 0, "spectrum3.presetX"}, {&spectrum3d.presetY, -0.1, 0, 0, "spectrum3.presetY"}, {&spectrum3d.presetZ, -1.05, 0, 0, "spectrum3.presetZ"}, {&spectrum3d.presetAngleH, -16.000000, 0, 0, "spectrum3.presetAngleH"}, {&spectrum3d.presetAngleV, 10.000000, 0, 0, "spectrum3.presetAngleV"}, {&spectrum3d.presetAngleZ, 0, 0, 0, "spectrum3.presetAngleZ"}, {&spectrum3d.zStep, 0.01, 0.005, 0.02, "spectrum3.zStep"}};

int sizeofPrefGbool = 2;
PreferenceGbool preferenceGbool[2] = {{&realtime, FALSE, "realtime"}, {&enableTouch, TRUE, "enableTouch"}};

int sizeofPrefString = 1;
char *preferenceString[1] = {policyName};
char prefStringPossibleValue[1][4][40] = {{"policyName", "SCHED_RR", "SCHED_RR", "SCHED_FIFO"}};

void set_default_values(){
	int i = 0;
	for (i = 0; i < sizeofPrefInt; i++){
		*preferenceInt[i].var = preferenceInt[i].def;
		}
	for (i = 0; i < sizeofPrefGLFloat; i++){
		*preferenceGLFloat[i].var = preferenceGLFloat[i].def;
		}
	for (i = 0; i < sizeofPrefGbool; i++){
		*preferenceGbool[i].var = preferenceGbool[i].def;
		}
	for (i = 0; i < sizeofPrefString; i++){
		if (strcmp(prefStringPossibleValue[i][1], "null") != 0){
			sprintf(preferenceString[i], "%s", prefStringPossibleValue[i][1]);
			}
		else {

			}
		}
}

void print_rc_file(const char *data){
	int i = 0;
	rcFile = fopen(rcPath, "w+");
	fprintf(rcFile, "# This is an spectrum3drc file autogenerated by Spectrum3d \n");
	for (i = 0; i < sizeofPrefInt ; i++){
		if (strcmp(data, "var") == 0){
			fprintf(rcFile, "# %s \n%d\n", preferenceInt[i].name, *preferenceInt[i].var);
			}
		else if (strcmp(data, "def") == 0){
			fprintf(rcFile, "# %s \n%d\n", preferenceInt[i].name, preferenceInt[i].def);
			}
		}
	for (i = 0; i < sizeofPrefGLFloat ; i++){
		if (strcmp(data, "var") == 0){
			fprintf(rcFile, "# %s \n%f\n", preferenceGLFloat[i].name, *preferenceGLFloat[i].var);
			}
		else if (strcmp(data, "def") == 0){
			fprintf(rcFile, "# %s \n%f\n", preferenceGLFloat[i].name, preferenceGLFloat[i].def);
			}
		}
	for (i = 0; i < sizeofPrefGbool ; i++){
		if (strcmp(data, "var") == 0){
			fprintf(rcFile, "# %s \n%d\n", preferenceGbool[i].name, *preferenceGbool[i].var);
			}
		else if (strcmp(data, "def") == 0){
			fprintf(rcFile, "# %s \n%d\n", preferenceGbool[i].name, preferenceGbool[i].def);
			}
		}
	for (i = 0; i < sizeofPrefString ; i++){
		if (strcmp(data, "var") == 0){
			fprintf(rcFile, "# %s \n%s\n", prefStringPossibleValue[i][0], preferenceString[i]);
			}
		else if (strcmp(data, "def") == 0){
			if (strcmp(prefStringPossibleValue[i][1], "null") != 0){
				fprintf(rcFile, "# %s \n%s\n", prefStringPossibleValue[i][0], prefStringPossibleValue[i][1]);
				}
			else {
				fprintf(rcFile, "# %s \n%s\n", prefStringPossibleValue[i][0], preferenceString[i]);
				}
			}
		}
	fclose(rcFile);
}

void compare_values(){
	int i = 0;
	gboolean error = FALSE, match = FALSE;
	printf("Checking values retrieved from rc file for consistency ");
	for (i = 0; i < sizeofPrefInt; i++){
		if (*preferenceInt[i].var < preferenceInt[i].min || *preferenceInt[i].var > preferenceInt[i].max){
			printf("\n'%s' seems out of range -> using default values and saving them as default\n", preferenceInt[i].name);
			set_default_values();
			print_rc_file("def");
			error = TRUE;
			}
		}
	for (i = 0; i < sizeofPrefString; i++){
		int a = 0;
		match = FALSE;
		for (a = 2; a < 4; a++){
			char *test = strstr(preferenceString[i], prefStringPossibleValue[i][a]);
			if (test != NULL){
				match = TRUE;
				}
			}
		if (match == FALSE){
			printf("\n'%s' seems not to be correct -> using default values and saving them as default\n", prefStringPossibleValue[i][0]);
			set_default_values();
			print_rc_file("def");
			i = sizeofPrefString;
			} 
		}
	if (error == FALSE && match == TRUE){
		printf("  ... OK\n");
		}
}

/* Get the saved values from the configuration file */
void get_saved_values(){
	char confString[105]="";
	int i = 0;

	//sprintf(prefPath, "%s/.spectrum3d/spectrum3d.pref", getenv("HOME"));
	sprintf(rcPath, "%s/.spectrum3d/spectrum3drc", g_get_home_dir());
	rcFile = fopen(rcPath, "r+"); 
	if (rcFile != NULL){
		printf("Opening the 'spectrum3drc' file and getting the saved values\n");
		char *result = NULL;
		while (i < sizeofPrefInt){ 
			result = fgets(confString, 100, rcFile); 
				if (strchr(confString, '#') == NULL){
					*preferenceInt[i].var = strtol(confString, NULL, 10);
					//printf("%s = %d\n", preferenceInt[i].name, *preferenceInt[i].var);
					i++;
					}
			}
		i = 0;
		while (i < sizeofPrefGLFloat){ 
			result = fgets(confString, 100, rcFile); 
				if (strchr(confString, '#') == NULL){
					*preferenceGLFloat[i].var = strtof(confString, NULL);
					//printf("%s = %f\n", preferenceFloat[i].name, *preferenceFloat[i].var);
					i++;
					}
			}
		i = 0;
		while (i < sizeofPrefGbool){ 
			result = fgets(confString, 100, rcFile); 
				if (strchr(confString, '#') == NULL){
					*preferenceGbool[i].var = strtol(confString, NULL, 10);
					//printf("%s = %d\n", preferenceGbool[i].name, *preferenceGbool[i].var);
					i++;
					}
			}
		i = 0;
		while (i < sizeofPrefString){ 
			result = fgets(confString, 100, rcFile); 
				if (strchr(confString, '#') == NULL){
					sprintf(preferenceString[i], "%s", confString);
					preferenceString[i][strlen(preferenceString[i])-1] = 0;
					//printf("%s = %s\n", prefStringPossibleValue[i][0], preferenceString[i]);
					i++;
					}
			}
		fclose(rcFile);	
		compare_values();
		}
	else {  
//If the 'preferences file doesn't exist, create one with default values
		printf ("WARNING : RC file doesn't exist or cannot be open; this is normal if you run Spectrum3d for the first time; \n");
		//rcFile = fopen(rcPath, "r+");
		set_default_values();
		print_rc_file("def");
		}
}



